name: Build, Test and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-build-package:
    name: Test with MSSQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSSQL
        uses: potatoqualitee/mssqlsuite@v1.8
        with:
          install: sqlengine, sqlclient, sqlpackage, localdb, fulltext
          version: 2019
          sa-password: Ankaramesui1@1@
          show-log: true

      - name: Verify MSSQL
        run: sqlcmd -S localhost -U sa -P Ankaramesui1@1@ -d tempdb -Q "SELECT @@version;" -C

      - name: Create Database
        run: |
          sqlcmd -S localhost -U sa -P Ankaramesui1@1@ -Q "CREATE DATABASE pfe;" -C -N

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run Tests
        run: mvn test

      - name: Package app
        run: mvn clean package -DskipTests
        env:
          SPRING_PROFILES_ACTIVE: prod

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

      - name: SonarCloud Analysis with Maven
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Ankaramesuiii_api-budget -Dsonar.organization=ankaramesuiii -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ vars.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: test-build-package

    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_21237F916FCA4077A519B0576487C32D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_413016D826A94C5F9CBE64E65D72A8D2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C55D1936AF2F412F83836A53EFEA063C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-budget'
          slot-name: 'Production'
          package: '*.jar'
          startup-command: 'java -Dspring.profiles.active=prod -jar api-budget.jar'
