name: Build, Test and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:  # This enables manual triggering of the workflow

jobs:
  test-with-mssql:
    name: Test with MSSQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSSQL
        uses: potatoqualitee/mssqlsuite@v1.8
        with:
          install: sqlengine, sqlclient, sqlpackage, localdb, fulltext
          version: 2019
          sa-password: Ankaramesui1@1@
          show-log: true

      - name: Verify MSSQL
        run: sqlcmd -S localhost -U sa -P Ankaramesui1@1@ -d tempdb -Q "SELECT @@version;" -C

      - name: Create Database
        run: |
          sqlcmd -S localhost -U sa -P Ankaramesui1@1@ -Q "CREATE DATABASE pfe;" -C -N

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Run unit tests
        run: mvn -B test --file pom.xml

  build-deploy:
    name: Build and Deploy API
    runs-on: ubuntu-latest
    needs: test-with-mssql
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
          if-no-files-found: error

  manual-deploy:
    name: Manual Deploy
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: application-jar

      - name: Show files for verification
        run: ls -la

      - name: Manual deploy step
        run: |
          echo "The JAR file has been built and is ready for deployment."
          echo "Add your deployment commands here or trigger them manually."
          echo "For security reasons, actual deployment commands are not included in this workflow."
        if: ${{ github.event_name == 'workflow_dispatch' }}